create table playable_audio (
  id integer generated by default as identity primary key,
  title text not null,
  published boolean not null default false,
  stream_blob_url text not null,
  download_blob_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table contacts (
  id integer generated by default as identity primary key,
  email text not null unique,
  name text null,
  role text null,
  instagram text null,
  x_handle text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contacts_role_check check (
    role is null or role in ('producer', 'artist', 'other')
  )
);

create table installs (
  id integer generated by default as identity primary key,
  contact_id integer not null references contacts (id) on delete restrict,
  playable_audio_id integer not null references playable_audio (id) on delete cascade,
  count integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint installs_count_check check (count >= 1),
  constraint installs_contact_audio_unique unique (contact_id, playable_audio_id)
);
